--Insert sample data into student table
INSERT INTO STUDENT (ID, STUDENT_NAME, CITY, AGE) VALUES(1, 'MAYANK', 'NAGPUR', 15);
INSERT INTO STUDENT (ID, STUDENT_NAME, CITY, AGE) VALUES(2, 'SMAUMYA', 'PUNE', 15);
INSERT INTO STUDENT (ID, STUDENT_NAME, CITY, AGE) VALUES(3, 'ALI', 'PUNE', 14);
INSERT INTO STUDENT (ID, STUDENT_NAME, CITY, AGE) VALUES(4, 'ARAYA', 'THANE', 14);
INSERT INTO STUDENT (ID, STUDENT_NAME, CITY, AGE) VALUES(5, 'RIYA', 'THANE', 16);
INSERT INTO STUDENT (ID, STUDENT_NAME, CITY, AGE) VALUES(6, 'YASH', 'JALGAON', 14);
INSERT INTO STUDENT (ID, STUDENT_NAME, CITY, AGE) VALUES(7, 'NARAYANI', 'AMRAVATI', 14);
INSERT INTO STUDENT (ID, STUDENT_NAME, CITY, AGE) VALUES(8 ,'RUHAN', 'KOLAPUR', 14);
INSERT INTO STUDENT (ID, STUDENT_NAME, CITY, AGE) VALUES(9 ,'HAARI', 'KOLAPUR', 15);
INSERT INTO STUDENT (ID, STUDENT_NAME, CITY, AGE) VALUES(10, 'PALLAV', 'THANE', 14);

COMMIT; --IT WILL SAVE VALUES
