-- Age greater than 15
SELECT STUDENT_NAME, CITY FROM STUDENT WHERE AGE > 15;

-- Student from Thane
SELECT STUDENT_NAME, AGE FROM STUDENT WHERE CITY = 'THANE';

-- Age less than 15
SELECT ID, STUDENT_NAME FROM STUDENT WHERE AGE < 15;

-- Student from Nagpur or Amravati
SELECT ID, STUDENT_NAME, CITY FROM STUDENT WHERE CITY = 'NAGPUR' OR CITY = 'AMRAVATI';

-- Student from Pune and age is 14;
SELECT STUDENT_NAME FROM STUDENT WHERE CITY = 'PUNE' AND AGE = 14;
