-- WAQTD NUMBER OF EMPLOYEES WORKING IN EACH DEPARTEMENT EXCEPT PRESIDENT.
SELECT DEPTNO, COUNT(*)
FROM EMP
WHERE JOB NOT IN ('PRESIDENT')
GROUP BY DEPTNO;

-- WAQTD TOTAL SALARY NEEDED TO PAY ALL THE EMPLOYEES IN EACH JOB. 
SELECT JOB, SUM(SAL)
FROM EMP
GROUP BY JOB;

-- WAQTD NUMBER OF EMPLOYEEES WORKING ASMANAGER IN EACH DEPARTMENT.
SELECT DEPTNO, COUNT(*) 
FROM EMP 
WHERE JOB = 'MANAGER' 
GROUP BY DEPTNO;

-- WAQTD AVG SALARY NEEDED TO PAY ALL THE EMPLOYEES IN EACH DEPARTMENT EXCLUDING THE EMPLOYEES OF DEPTNO 20.
SELECT DEPTNO, AVG(SAL)
FROM EMP
WHERE DEPTNO NOT IN (20)
GROUP BY DEPTNO;

-- WAQTD NUMBER OF EMPLOYEES HAVING CHARACTER 'A' IN THEIR NAMES IN EACH JOB.
SELECT JOB, COUNT(*)
FROM EMP
WHERE LOCATE('A', ENAME) > 0
GROUP BY JOB;

-- WAQTD NUMBER OF EMPLOYEES AND AVG SALARY NEEDED TO PAY THE EMPLOYEES WHO SALARY IN GREATER THAN 2000 IN EACH DEPT.
SELECT DEPTNO, COUNT(*), AVG(SAL)
FROM EMP
WHERE SAL > 2000
GROUP BY DEPTNO;

-- WAQDTD TOTAL SALARY NEEDED TO PAY AND NUMBER OF SALESMANS IN EACH DEPT
SELECT DEPTNO, SUM(SAL)
FROM EMP
WHERE JOB = 'SALESMAN'
GROUP BY DEPTNO;

-- WAQTD NUMBER OF EMPLOYEES WITH THEIR MAXIMUM SALARIES IN EACH JOB.
SELECT JOB, COUNT(*), MAX(SAL)
FROM EMP
GROUP BY JOB;

-- WAQTD MAXIMUM SALARIES GIVEN TO AN EMPLOYEE WORKING IN EACH DEPT
SELECT DEPTNO, MAX(SAL)
FROM EMP
GROUP BY DEPTNO;

-- WAQTD NUMBER OF TIMES THE SALARIES PRESENT IN EMPLOYEE TABLE.
SELECT SAL, COUNT(*)
FROM EMP
GROUP BY SAL;

-- Display department number and total salary paid in each department.
SELECT DEPTNO, COUNT(SAL), SUM(SAL)
FROM EMP
GROUP BY DEPTNO;

-- Display department number and number of employees in each department.
SELECT DEPTNO, COUNT(*)
FROM EMP
GROUP BY DEPTNO;

-- Display job and average salary for each job.
SELECT JOB, AVG(SAL)
FROM EMP
GROUP BY JOB;

-- Display job and maximum salary for each job.
SELECT JOB, MAX(SAL)
FROM EMP
GROUP BY JOB;

-- Display department number and minimum salary in each department.
SELECT DEPTNO, MIN(SAL)
FROM EMP
GROUP BY DEPTNO;

-- Display department number and number of employees earning more than 2000.
SELECT DEPTNO, COUNT(*)
FROM EMP
WHERE SAL > 2000
GROUP BY DEPTNO;

-- Display job and total salary of employees working as that job.
SELECT JOB, SUM(SAL)
FROM EMP
GROUP BY JOB;

-- Display department number and maximum salary, only for departments having employees.
SELECT DEPTNO, MAX(SAL)
FROM EMP
GROUP BY DEPTNO;

-- Display job and count of employees hired after 1982.
SELECT JOB, COUNT(*)
FROM EMP
WHERE DATE_FORMAT(HIREDATE, '%Y') > 1982
GROUP BY JOB;

-- Display department number and average salary of employees getting commission.
SELECT DEPTNO, AVG(SAL)
FROM EMP
WHERE COMM IS NOT NULL
GROUP BY DEPTNO;
