-- WAQTD DNO AND NUMBER OF EMP WORKING IN EACH DEPT IF THERE ARE ATLEAST 2 CLERKS IN EACH DEPT 
SELECT DEPTNO, COUNT(*)
FROM EMP
WHERE JOB = 'CLERK'
GROUP BY DEPTNO 
HAVING COUNT(*) >= 2;

-- WAQTD DNO AND TOTAL SAALARYNEEDED TO PAY ALL EMP IN EACH DEPT IF THERE ARE ATLEAST 4 EMP IN EACH DEPT
SELECT DEPTNO, SUM(SAL) 
FROM EMP 
GROUP BY DEPTNO 
HAVING COUNT(*) >= 4;

-- WAQTD NUMBER OF EMP EARNING SAL MORE THAN 1200 IN EACH JOB AND THE TOTAL SAL NEEDED TO PAY EMP OF EACH JOB MUST EXCEES 3800
SELECT JOB, COUNT(*), SUM(SAL) 
FROM EMP 
WHERE SAL > 1200 
GROUP BY JOB 
HAVING SUM(SAL) > 3800;

-- WAQTD DEPTNO AND NUMBER OF EMP WORKING ONLY IF THERE ARE 2 EMP WORKING IN EACH DEPT AS MANAGER .
SELECT DEPTNO, COUNT(*) 
FROM EMP 
WHERE JOB = 'MANAGER' 
GROUP BY DEPTNO 
HAVING COUNT(*) = 2;

-- WAQTD JOB AND MAX SAL OF EMP IN EACH JOB IF THE MAX SAL EXCEEDS 2600
SELECT JOB, MAX(SAL) 
FROM EMP 
GROUP BY JOB 
HAVING MAX(SAL) > 2600;

-- WAQTD THE SALARIES WHICH ARE REPEATED IN EMP TABLE
SELECT SAL
FROM EMP
GROUP BY SAL
HAVING COUNT(*) > 1;

-- WAQTD THE HIREDATE WHICH ARE DUPLICATED IN EMP TABLE
SELECT HIREDATE
FROM EMP
GROUP BY HIREDATE
HAVING COUNT(*) > 1;

-- WAQTD AVG SALARY OF EACH DEPT IF AVG SAL IS LESS THAN 3000
SELECT DEPTNO, AVG(SAL)
FROM EMP
GROUP BY DEPTNO
HAVING AVG(SAL) < 3000;

-- .WAQTD DEPTNO IF THERE ARE ATLEAST 3 EMP IN EACH DEPT WHOS NAME HAS CHAR 'A' OR 'S'
SELECT DEPTNO, COUNT(*) 
FROM EMP 
WHERE ENAME LIKE '%A%' OR ENAME LIKE '%S%'  
GROUP BY DEPTNO 
HAVING COUNT(*) >= 3;

-- WAQTD MIN AND MAX SALARIES OF EACH JOB IF MIN SAL IS MORE THAN 1000 AND MAX SAL IS LESS THAN 5000.
SELECT JOB, MIN(SAL), MAX(SAL) 
FROM EMP 
GROUP BY JOB 
HAVING MIN(SAL) > 1000 AND MAX(SAL) < 5000;

-- Display departments having more than 3 employees.
SELECT DEPTNO, COUNT(*) 
FROM EMP 
GROUP BY DEPTNO 
HAVING COUNT(*) > 3;

-- Display jobs where average salary is greater than 2500.
SELECT JOB, AVG(SAL) 
FROM EMP 
GROUP BY JOB 
HAVING AVG(SAL) > 2500;

-- Display departments where total salary is more than 9000.
SELECT DEPTNO, SUM(SAL) 
FROM EMP 
GROUP BY DEPTNO 
HAVING SUM(SAL) > 9000;

-- Display jobs having at least 2 employees.
SELECT JOB, COUNT(*) 
FROM EMP 
GROUP BY JOB 
HAVING COUNT(*) >= 2;

-- Display departments where maximum salary is greater than 4000.
SELECT DEPTNO, MAX(SAL) 
FROM EMP 
GROUP BY DEPTNO 
HAVING MAX(SAL) > 4000;

-- Display jobs where minimum salary is less than 1500.
SELECT JOB, MIN(SAL) 
FROM EMP 
GROUP BY JOB 
HAVING MIN(SAL) < 1500;

-- Display departments having more than 2 employees earning salary above 2000.
SELECT DEPTNO, COUNT(*) 
FROM EMP 
WHERE SAL > 2000 
GROUP BY DEPTNO 
HAVING COUNT(*) > 2;

-- Display jobs where total salary is greater than 10000.
SELECT JOB, SUM(SAL) 
FROM EMP 
GROUP BY JOB 
HAVING SUM(SAL) > 10000;

--  Display departments where average salary is between 2000 and 4000.
SELECT DEPTNO, AVG(SAL) 
FROM EMP 
GROUP BY DEPTNO 
HAVING AVG(SAL) BETWEEN 2000 AND 4000;

-- Display jobs having only one employee.
SELECT JOB, COUNT(*)
FROM EMP
GROUP BY JOB
HAVING COUNT(*) = 1;

-- Display departments having at least 3 employees earning salary greater than 1500.
SELECT DEPTNO, COUNT(*) 
FROM EMP 
WHERE SAL > 1500 
GROUP BY DEPTNO 
HAVING COUNT(*) >= 3;

-- Display jobs where total salary of employees exceeds 8000.
SELECT JOB, SUM(SAL)
FROM EMP
GROUP BY JOB
HAVING SUM(SAL) > 8000;

-- Display departments where minimum salary is greater than 1000.
SELECT DEPTNO, MIN(SAL)
FROM EMP
GROUP BY DEPTNO
HAVING MIN(SAL) > 1000;

-- Display jobs having more than 2 employees whose names contain letter 'A'.
SELECT JOB, COUNT(*)
FROM EMP
WHERE LOCATE('A', ENAME) > 0
GROUP BY JOB
HAVING COUNT(*) > 2;

-- Display departments where average salary is less than 3000 and employee count is more than 3.
SELECT DEPTNO, AVG(SAL)
FROM EMP
GROUP BY DEPTNO
HAVING AVG(SAL) < 3000 AND COUNT(*) > 3;

-- Display jobs where maximum salary is between 2500 and 5000.
SELECT JOB, MAX(SAL)
FROM EMP
GROUP BY JOB
HAVING MAX(SAL) BETWEEN 2500 AND 5000;

-- Display departments having at least 2 employees getting commission.
SELECT DEPTNO, COUNT(*)
FROM EMP
WHERE COMM IS NOT NULL AND COMM > 0
GROUP BY DEPTNO
HAVING COUNT(*) >= 2;

-- Display jobs where total salary of employees earning more than 2000 exceeds 6000.
SELECT JOB, SUM(SAL)
FROM EMP
WHERE SAL > 2000
GROUP BY JOB
HAVING SUM(SAL) > 6000;

-- Display departments having exactly 3 employees.
SELECT DEPTNO, COUNT(*)
FROM EMP
GROUP BY DEPTNO
HAVING COUNT(*) = 3;

-- Display jobs where more than one employee shares the same salary.
SELECT DISTINCT JOB
FROM EMP 
GROUP BY JOB, SAL 
HAVING COUNT(*) > 1;
