--case1: -
-- WAQTD NAME OF THE EMPLOYEES EARNING MORE THAN ADAMS
SELECT ENAME
FROM EMP
WHERE SAL > (SELECT SAL
             FROM EMP
             WHERE ENAME = 'ADAMS');

-- WAQTD NAME AND SALARY OF THE EMPLOYEES EARNING LESS THAN KING
SELECT ENAME, SAL
FROM EMP
WHERE SAL < (SELECT SAL
             FROM EMP
             WHERE ENAME = 'KING');

-- WAQTD NAME AND DEPTNO OF THE EMPLOYEES IF THEY ARE WORKING IN THE SAME DEPT AS JONES 
SELECT ENAME, DEPTNO
FROM EMP
WHERE DEPTNO = (SELECT DEPTNO
                FROM EMP
                WHERE ENAME = 'JONES');

-- WAQTD NAME AND JOB OF ALL THE EMPLOYEES WORKING IN THE SAME DESIGNATION AS JAMES 
SELECT ENAME, JOB
FROM EMP
WHERE JOB = (SELECT JOB
             FROM EMP
             WHERE ENAME = 'JAMES');

-- WAQTD EMPNO AND ENAME ALONG WITH ANNUAL SALARY OF ALL THEEMPLOYEES IF THEIR ANNUAL SALARY IS GREATER THAN WARDS ANNUAL SALARY.
SELECT EMPNO, ENAME, SAL*12 AS ANNUAL_SAL
FROM EMP 
WHERE SAL*12 > (SELECT SAL*12 
                FROM EMP 
                WHERE ENAME = 'WARD');

-- WAQTD NAME AND HIREDATE OF THE EMPLOYEES IF THEY ARE HIRED BEFORE SCOTT 
SELECT ENAME, HIREDATE
FROM EMP
WHERE HIREDATE < (SELECT HIREDATE
                  FROM EMP
                  WHERE ENAME = 'SCOTT');

-- WAQTD NAME AND HIREDATE OF THE EMPLOYEES IF THEY ARE HIRED AFTER THE PRESIDENT
SELECT ENAME, HIREDATE
FROM EMP
WHERE HIREDATE > (SELECT HIREDATE
                  FROM EMP
                  WHERE JOB = 'PRESIDENT');

-- WAQTD NAME AND SAL OF THE EMPLOYEE IF THEY ARE EARNING SAL LESS THAN THE EMPLOYEE WHOS EMPNO IS 7839
SELECT ENAME, SAL
FROM EMP
WHERE SAL < (SELECT SAL
             FROM EMP
             WHERE EMPNO = 7839);

-- WAQTD ALL THE DETAILS OF THE EMPLOYEES IF THE EMPLOYEES ARE HIRED BEFORE MILLER
SELECT *
FROM EMP
WHERE HIREDATE < (SELECT HIREDATE
                  FROM EMP
                  WHERE ENAME = 'MILLER');

-- WAQTD ENAME AND EMPNO OF THE EMPLOYEES IF EMPLOYEES ARE EARNING MORE THAN ALLEN
SELECT ENAME, EMPNO
FROM EMP
WHERE SAL > (SELECT SAL 
             FROM EMP
             WHERE ENAME = 'ALLEN');

-- WAQTD ENAME AND SALARY OF ALL THE EMPLOYEES WHO ARE EARNING MORE THAN MILLER BUT LESS THAN ALLEN.
SELECT ENAME, SAL
FROM EMP
WHERE SAL > (SELECT SAL
             FROM EMP
             WHERE ENAME = 'MILLER') AND SAL < (SELECT SAL
                                                FROM EMP
                                                WHERE ENAME = 'ALLEN');

-- WAQTD ALL THE DETAILS OF THE EMPLOYEES WORKING IN DEPT 20 AND WORKING IN THE SAME DESIGNATION AS SMITH 
SELECT *
FROM EMP
WHERE DEPTNO = 20 AND JOB = (SELECT JOB
                             FROM EMP
                             WHERE ENAME = 'SMITH');

-- WAQTD ALL THE DETAILS OF THE EMPLOYEES WORKING AS MANAGER IN THE SAME DEPT AS TURNER
SELECT * 
FROM EMP
WHERE JOB = 'MANAGER' AND DEPTNO = (SELECT DEPTNO
                                    FROM EMP
                                    WHERE ENAME = 'TURNER');

-- WAQTD NAME AND HIREDATE OF THE EMPLOYEES HIRED AFTER 1980 AND BEFORE KING
SELECT ENAME, HIREDATE
FROM EMP
WHERE HIREDATE > '1980-12-31' AND HIREDATE < (SELECT HIREDATE
                                              FROM EMP
                                              WHERE ENAME = 'KING');

-- WAQTD NAME AND SAL ALONG WITH ANNUAL SAL FOR ALL EMPLOYEES WHOS SAL IS LESS THAN BLAKE AND MORE THAN 3500
SELECT ENAME, SAL, SAL*12 AS ANNUAL_SAL 
FROM EMP 
WHERE SAL > (SELECT SAL 
             FROM EMP 
             WHERE ENAME = 'BLAKE') AND SAL > 3500;

-- WAQTD ALL THE DETAILS OF EMPLOYEES WHO EARN MORE THAN SCOTT BUT LESS THAN KING 
SELECT *
FROM EMP
WHERE SAL > (SELECT SAL
             FROM EMP
             WHERE ENAME = 'SCOTT') AND SAL < (SELECT SAL
                                               FROM EMP
                                               WHERE ENAME = 'KING');


-- WAQTD NAME OF THE EMPLOYEES WHOS NAME STARTS WITH 'A' AND WORKS IN THE SAME DEPT AS BLAKE
SELECT ENAME
FROM EMP
WHERE ENAME LIKE 'A%' AND DEPTNO = (SELECT DEPTNO
                                    FROM EMP
                                    WHERE ENAME = 'BLAKE');


--  WAQTD NAME AND COMM IF EMPLOYEES EARN COMISSION AND WORK IN THE SAME DESIGNATION AS SMITH
SELECT ENAME, COMM
FROM EMP
WHERE COMM IS NOT NULL AND JOB = (SELECT JOB
                                 FROM EMP
                                 WHERE ENAME = 'SMITH');

-- WAQTD DETAILS OF ALL THE EMPLOYEES WORKING AS CLERK IN THE SAME DEPT AS TURNER .
SELECT *
FROM EMP
WHERE JOB = 'CLERK' AND DEPTNO = (SELECT DEPTNO
                                  FROM EMP
                                  WHERE ENAME = 'TURNER');

-- WAQTD ENAME, SAL AND DESIGNATION OF THE EMPLOYEES WHOS ANNUAL SALARY IS MORE THAN SMITH AND LESS THAN KING
SELECT ENAME, SAL, JOB 
FROM EMP
WHERE SAL*12 > (SELECT SAL*12
                FROM EMP
                WHERE ENAME = 'SMITH') AND SAL*12 < (SELECT SAL*12
                                                 FROM EMP
                                                 WHERE ENAME = 'KING');


-- case 2: -
-- WAQTD DNAME OF THE EMPLOYEES WHOS NAME IS SMITH
SELECT DNAME
FROM DEPT
WHERE DEPTNO = (SELECT DEPTNO
                 FROM EMP
                 WHERE ENAME = 'SMITH');

-- WAQTD DNAME AND LOC OF THE EMPLOYEE WHOS ENAME IS KING
SELECT DNAME, LOC
FROM DEPT
WHERE DEPTNO = (SELECT DEPTNO
                FROM EMP
                WHERE ENAME = 'KING');

-- WAQTD LOC OF THE EMP WHOS EMPLOYEE NUMBER IS 7902
SELECT LOC
FROM DEPT
WHERE DEPTNO = (SELECT DEPTNO
                FROM EMP
                WHERE EMPNO = 7902);

-- WAQTD DNAME AND LOC ALONG WITH DEPTNO OF THE EMPLOYEE WHOS NAME ENDS WITH 'R' .
SELECT DNAME, LOC
FROM DEPT
WHERE DEPTNO = (SELECT DEPTNO
                FROM EMP
                WHERE ENAME LIKE '%R');

-- WAQTD DNAME OF THE EMPLOYEE WHOS DESIGNATION IS PRESIDENT
SELECT DNAME
FROM DEPT
WHERE DEPTNO = (SELECT DEPTNO
                FROM EMP
                WHERE JOB = 'PRESIDENT');

--  WAQTD NAMES OF THE EMPLOYEES WORKING IN ACCOUNTING DEPARTMENT
SELECT ENAME
FROM EMP
WHERE DEPTNO = (SELECT DEPTNO
                FROM DEPT
                WHERE DNAME = 'ACCOUNTING');

-- WAQTD ENAME AND SALARIES OF THE EMPLOYEES WHO ARE WORKING IN THE LOCATION CHICAGO
SELECT ENAME, SAL
FROM EMP
WHERE DEPTNO = (SELECT DEPTNO
                FROM DEPT
                WHERE LOC = 'CHICAGO');

-- WAQTD DETAILS OF THE EMPLOYEES WORKING IN SALES
SELECT *
FROM EMP
WHERE DEPTNO = (SELECT DEPTNO
                FROM DEPT
                WHERE DNAME = 'SALES');

-- WAQTD DETAILS OF THE EMP ALONG WITH ANNUAL SALARY IF EMPLOYEES ARE WORKING IN NEW YORK 
SELECT *, SAL*12 AS ANNUAL_SAL
FROM EMP
WHERE DEPTNO = (SELECT DEPTNO
                FROM DEPT
                WHERE LOC = 'NEW YORK');

-- WAQTD NAMES OF EMPLOYEES WORKING IN OPERATIONS DEPARTMENT
SELECT ENAME
FROM EMP
WHERE DEPTNO = (SELECT DEPTNO
                FROM DEPT
                WHERE DNAME = 'OPERATIONS');


