-- case 1 & case 2 : -
-- WAQTD NAME OF THE EMPLOYEES EARNING MORE THAN ADAMS
SELECT ENAME
FROM EMP
WHERE SAL > (SELECT SAL
             FROM EMP
             WHERE ENAME = 'ADAMS');

-- WAQTD NAME AND SALARY OF THE EMPLOYEES EARNING LESS THAN KING
SELECT ENAME, SAL
FROM EMP
WHERE SAL < (SELECT SAL
             FROM EMP
             WHERE ENAME = 'KING');

-- WAQTD NAME AND DEPTNO OF THE EMPLOYEES IF THEY ARE WORKING IN THE SAME DEPT AS JONES 
SELECT ENAME, DEPTNO
FROM EMP
WHERE DEPTNO = (SELECT DEPTNO
                FROM EMP
                WHERE ENAME = 'JONES');

-- WAQTD NAME AND JOB OF ALL THE EMPLOYEES WORKING IN THE SAME DESIGNATION AS JAMES 
SELECT ENAME, JOB
FROM EMP
WHERE JOB = (SELECT JOB
             FROM EMP
             WHERE ENAME = 'JAMES');

-- WAQTD EMPNO AND ENAME ALONG WITH ANNUAL SALARY OF ALL THEEMPLOYEES IF THEIR ANNUAL SALARY IS GREATER THAN WARDS ANNUAL SALARY.
SELECT EMPNO, ENAME, SAL*12 AS ANNUAL_SAL
FROM EMP 
WHERE SAL*12 > (SELECT SAL*12 
                FROM EMP 
                WHERE ENAME = 'WARD');

-- WAQTD NAME AND HIREDATE OF THE EMPLOYEES IF THEY ARE HIRED BEFORE SCOTT 
SELECT ENAME, HIREDATE
FROM EMP
WHERE HIREDATE < (SELECT HIREDATE
                  FROM EMP
                  WHERE ENAME = 'SCOTT');

-- WAQTD NAME AND HIREDATE OF THE EMPLOYEES IF THEY ARE HIRED AFTER THE PRESIDENT
SELECT ENAME, HIREDATE
FROM EMP
WHERE HIREDATE > (SELECT HIREDATE
                  FROM EMP
                  WHERE JOB = 'PRESIDENT');

-- WAQTD NAME AND SAL OF THE EMPLOYEE IF THEY ARE EARNING SAL LESS THAN THE EMPLOYEE WHOS EMPNO IS 7839
SELECT ENAME, SAL
FROM EMP
WHERE SAL < (SELECT SAL
             FROM EMP
             WHERE EMPNO = 7839);

-- WAQTD ALL THE DETAILS OF THE EMPLOYEES IF THE EMPLOYEES ARE HIRED BEFORE MILLER
SELECT *
FROM EMP
WHERE HIREDATE < (SELECT HIREDATE
                  FROM EMP
                  WHERE ENAME = 'MILLER');

-- WAQTD ENAME AND EMPNO OF THE EMPLOYEES IF EMPLOYEES ARE EARNING MORE THAN ALLEN
SELECT ENAME, EMPNO
FROM EMP
WHERE SAL > (SELECT SAL 
             FROM EMP
             WHERE ENAME = 'ALLEN');

-- WAQTD ENAME AND SALARY OF ALL THE EMPLOYEES WHO ARE EARNING MORE THAN MILLER BUT LESS THAN ALLEN.
SELECT ENAME, SAL
FROM EMP
WHERE SAL > (SELECT SAL
             FROM EMP
             WHERE ENAME = 'MILLER') AND SAL < (SELECT SAL
                                                FROM EMP
                                                WHERE ENAME = 'ALLEN');

-- WAQTD ALL THE DETAILS OF THE EMPLOYEES WORKING IN DEPT 20 AND WORKING IN THE SAME DESIGNATION AS SMITH 
SELECT *
FROM EMP
WHERE DEPTNO = 20 AND JOB = (SELECT JOB
                             FROM EMP
                             WHERE ENAME = 'SMITH');

-- WAQTD ALL THE DETAILS OF THE EMPLOYEES WORKING AS MANAGER IN THE SAME DEPT AS TURNER
SELECT * 
FROM EMP
WHERE JOB = 'MANAGER' AND DEPTNO = (SELECT DEPTNO
                                    FROM EMP
                                    WHERE ENAME = 'TURNER');

-- WAQTD NAME AND HIREDATE OF THE EMPLOYEES HIRED AFTER 1980 AND BEFORE KING
SELECT ENAME, HIREDATE
FROM EMP
WHERE HIREDATE > '1980-12-31' AND HIREDATE < (SELECT HIREDATE
                                              FROM EMP
                                              WHERE ENAME = 'KING');

-- WAQTD NAME AND SAL ALONG WITH ANNUAL SAL FOR ALL EMPLOYEES WHOS SAL IS LESS THAN BLAKE AND MORE THAN 3500
SELECT ENAME, SAL, SAL*12 AS ANNUAL_SAL 
FROM EMP 
WHERE SAL > (SELECT SAL 
             FROM EMP 
             WHERE ENAME = 'BLAKE') AND SAL > 3500;

-- WAQTD ALL THE DETAILS OF EMPLOYEES WHO EARN MORE THAN SCOTT BUT LESS THAN KING 
SELECT *
FROM EMP
WHERE SAL > (SELECT SAL
             FROM EMP
             WHERE ENAME = 'SCOTT') AND SAL < (SELECT SAL
                                               FROM EMP
                                               WHERE ENAME = 'KING');


-- WAQTD NAME OF THE EMPLOYEES WHOS NAME STARTS WITH 'A' AND WORKS IN THE SAME DEPT AS BLAKE
SELECT ENAME
FROM EMP
WHERE ENAME LIKE 'A%' AND DEPTNO = (SELECT DEPTNO
                                    FROM EMP
                                    WHERE ENAME = 'BLAKE');


--  WAQTD NAME AND COMM IF EMPLOYEES EARN COMISSION AND WORK IN THE SAME DESIGNATION AS SMITH
SELECT ENAME, COMM
FROM EMP
WHERE COMM IS NOT NULL AND JOB = (SELECT JOB
                                 FROM EMP
                                 WHERE ENAME = 'SMITH');

-- WAQTD DETAILS OF ALL THE EMPLOYEES WORKING AS CLERK IN THE SAME DEPT AS TURNER .
SELECT *
FROM EMP
WHERE JOB = 'CLERK' AND DEPTNO = (SELECT DEPTNO
                                  FROM EMP
                                  WHERE ENAME = 'TURNER');

-- WAQTD ENAME, SAL AND DESIGNATION OF THE EMPLOYEES WHOS ANNUAL SALARY IS MORE THAN SMITH AND LESS THAN KING
SELECT ENAME, SAL, JOB 
FROM EMP
WHERE SAL*12 > (SELECT SAL*12
                FROM EMP
                WHERE ENAME = 'SMITH') AND SAL*12 < (SELECT SAL*12
                                                 FROM EMP
                                                 WHERE ENAME = 'KING');


-- WAQTD DNAME OF THE EMPLOYEES WHOS NAME IS SMITH
SELECT DNAME
FROM DEPT
WHERE DEPTNO = (SELECT DEPTNO
                 FROM EMP
                 WHERE ENAME = 'SMITH');

-- WAQTD DNAME AND LOC OF THE EMPLOYEE WHOS ENAME IS KING
SELECT DNAME, LOC
FROM DEPT
WHERE DEPTNO = (SELECT DEPTNO
                FROM EMP
                WHERE ENAME = 'KING');

-- WAQTD LOC OF THE EMP WHOS EMPLOYEE NUMBER IS 7902
SELECT LOC
FROM DEPT
WHERE DEPTNO = (SELECT DEPTNO
                FROM EMP
                WHERE EMPNO = 7902);

-- WAQTD DNAME AND LOC ALONG WITH DEPTNO OF THE EMPLOYEE WHOS NAME ENDS WITH 'R' .
SELECT DNAME, LOC
FROM DEPT
WHERE DEPTNO = (SELECT DEPTNO
                FROM EMP
                WHERE ENAME LIKE '%R');

-- WAQTD DNAME OF THE EMPLOYEE WHOS DESIGNATION IS PRESIDENT
SELECT DNAME
FROM DEPT
WHERE DEPTNO = (SELECT DEPTNO
                FROM EMP
                WHERE JOB = 'PRESIDENT');

--  WAQTD NAMES OF THE EMPLOYEES WORKING IN ACCOUNTING DEPARTMENT
SELECT ENAME
FROM EMP
WHERE DEPTNO = (SELECT DEPTNO
                FROM DEPT
                WHERE DNAME = 'ACCOUNTING');

-- WAQTD ENAME AND SALARIES OF THE EMPLOYEES WHO ARE WORKING IN THE LOCATION CHICAGO
SELECT ENAME, SAL
FROM EMP
WHERE DEPTNO = (SELECT DEPTNO
                FROM DEPT
                WHERE LOC = 'CHICAGO');

-- WAQTD DETAILS OF THE EMPLOYEES WORKING IN SALES
SELECT *
FROM EMP
WHERE DEPTNO = (SELECT DEPTNO
                FROM DEPT
                WHERE DNAME = 'SALES');

-- WAQTD DETAILS OF THE EMP ALONG WITH ANNUAL SALARY IF EMPLOYEES ARE WORKING IN NEW YORK 
SELECT *, SAL*12 AS ANNUAL_SAL
FROM EMP
WHERE DEPTNO = (SELECT DEPTNO
                FROM DEPT
                WHERE LOC = 'NEW YORK');

-- WAQTD NAMES OF EMPLOYEES WORKING IN OPERATIONS DEPARTMENT
SELECT ENAME
FROM EMP
WHERE DEPTNO = (SELECT DEPTNO
                FROM DEPT
                WHERE DNAME = 'OPERATIONS');

-- WAQTD NAMES OF THE EMPLOYEES EARNING MORE THAN SCOTT IN ACCOUNTING DEPT
SELECT ENAME 
FROM EMP 
WHERE SAL > (SELECT SAL 
             FROM EMP 
             WHERE ENAME = 'SCOTT') AND DEPTNO IN (SELECT DEPTNO  
                                                   FROM DEPT
                                                   WHERE DNAME = 'ACCOUNTING');

 -- WAQTD DETAILS OF THE EMPLOYEES WORKING AS MANAGER IN THE LOCATION CHICAGO
SELECT * 
FROM EMP 
WHERE JOB = 'MANAGER' AND DEPTNO IN (SELECT DEPTNO 
                                     FROM DEPT 
                                     WHERE LOC = 'CHICAGO');

-- WAQTD NAME AND SAL OF THE EMPLOYEES EARNING MORE THAN KING IN THE DEPT ACCOUNTING 
SELECT ENAME, SAL 
FROM EMP 
WHERE SAL > (SELECT SAL
             FROM EMP
             WHERE ENAME = 'KING') AND DEPTNO IN (SELECT DEPTNO 
                                                  FROM DEPT 
                                                  WHERE DNAME = 'ACCOUNTING');

-- WAQTD DETAILS OF THE EMPLOYEES WORKING AS SALESMAN IN THE DEPARTEMENT SALES
SELECT * 
FROM EMP 
WHERE JOB = 'SALESMAN' AND DEPTNO IN (SELECT DEPTNO 
                                      FROM DEPT 
                                      WHERE DNAME = 'SALES');

-- WAQTD NAME , SAL , JOB , HIREDATE OF THE EMPLOYEES WORKING IN OPERATIONS DEPARTMENT AND HIRED BEFORE KING 
SELECT ENAME, SAL, JOB, HIREDATE 
FROM EMP 
WHERE DEPTNO IN (SELECT DEPTNO 
                 FROM DEPT 
                 WHERE DNAME = 'OPERATIONS') AND HIREDATE < 
                 (SELECT HIREDATE 
                 FROM EMP 
                 WHERE ENAME = 'KING');

-- DISPLAY ALL THE EMPLOYEES WHOSE DEPARTMET NAMES ENDING 'S'
SELECT * 
FROM EMP 
WHERE DEPTNO IN (SELECT DEPTNO 
                 FROM DEPT 
                 WHERE DNAME LIKE '%S');

-- WAQTD DNAME OF THE EMPLOYEES WHOS NAMES HAS CHARACTER 'A' IN IT.
SELECT DNAME 
FROM DEPT 
WHERE DEPTNO IN (SELECT DEPTNO 
                 FROM EMP 
                 WHERE LOCATE('A', ENAME) > 0);

-- WAQTD DNAME AND LOC OF THE EMPLOYEES WHOS SALARY IS RUPEES 800.
SELECT DNAME, LOC 
FROM DEPT 
WHERE DEPTNO IN (SELECT DEPTNO 
                 FROM EMP 
                 WHERE SAL = 800);

-- WAQTD DNAME OF THE EMPLOYEES WHO EARN COMISSION
SELECT DNAME 
FROM DEPT 
WHERE DEPTNO IN (SELECT DEPTNO 
                 FROM EMP 
                 WHERE COMM IS NOT NULL AND COMM > 0);

-- WAQTD LOC OF THE EMPLOYEES IF THEY EARN COMISSION IN DEPT 40 
SELECT LOC 
FROM DEPT 
WHERE DEPTNO IN (SELECT DEPTNO 
                 FROM EMP 
                 WHERE COMM IS NOT NULL AND COMM > 0 AND
                 DEPTNO = 40);

-- MAX & MIN
-- WAQTD NAME OF THE EMPLOYEE EARNING MAXIMUM SALARY
SELECT ENAME
FROM EMP
WHERE SAL = (SELECT MAX(SAL)
             FROM EMP);

-- WAQTD NAME OF THE EMPLOYEE EARNING MINIMUM SALARY 
SELECT ENAME
FROM EMP
WHERE SAL = (SELECT MIN(SAL)
             FROM EMP);

-- WAQTD NAME AND HIREDATE OF THE EMPLOYEE HIRED BEFORE ALL THE EMPLOYEES (FIRST EMP)
SELECT ENAME, HIREDATE
FROM EMP
WHERE HIREDATE = (SELECT MIN(HIREDATE)
                  FROM EMP);

-- WAQTD NAME AND HIREDATE OF THE EMPLOYEES HIRED AT THE LAST
SELECT ENAME, HIREDATE
FROM EMP
WHERE HIREDATE = (SELECT MAX(HIREDATE)
                  FROM EMP);

-- WAQTD NAME, COMM OF THE EMPLOYEE WHO EARNS MIN COMISSION 
SELECT ENAME, COMM
FROM EMP
WHERE COMM = (SELECT MIN(COMM)
              FROM EMP
              WHERE COMM IS NOT NULL);

-- WAQTD NAME, SAL AND COMM OF THE EMPLOYEE EARNING MAXIMUM COMISSION
SELECT ENAME, SAL, COMM
FROM EMP
WHERE COMM = (SELECT MAX(COMM)
              FROM EMP
              WHERE COMM IS NOT NULL);

-- WAQTD DETAILS OF THE EMPLOYEE WHO HAS GREATEST EMPNO 
SELECT *
FROM EMP
WHERE EMPNO = (SELECT MAX(EMPNO)
               FROM EMP);

-- WAQTD DETAILS OF THE EMPLOYEES HAVING THE LEAST EMPNO
SELECT *
FROM EMP
WHERE EMPNO = (SELECT MIN(EMPNO)
               FROM EMP);

-- WAQTD DETAILS OF THE EMPLOYEES EARNING LEAST ANNUAL SALARY 
SELECT *
FROM EMP
WHERE SAL*12 = (SELECT MIN(SAL*12)
                FROM EMP);

-- WAQTD NAME , ANNUAL SALARY OF THE EMPLOYEES IF THEIR ANNUAL SALARY IS MORE THAN ALL THE SALESMAN
SELECT ENAME, SAL*12 AS ANNUAL_SAL
FROM EMP
WHERE SAL*12 > (SELECT MAX(SAL*12)
                FROM EMP
                WHERE JOB = 'SALESMAN');

-- Nested Sub-Query (MAX & MIN)
-- WAQTD 2ND MINIMUM SALARY 
SELECT MIN(SAL)
FROM EMP
WHERE SAL > (SELECT MIN(SAL)
             FROM EMP);

-- WAQTD 5TH MAXIMUM SALARY
SELECT MAX(SAL)
FROM EMP
WHERE SAL < (SELECT MAX(SAL)
             FROM EMP
             WHERE SAL < (SELECT MAX(SAL)
                          FROM EMP
                          WHERE SAL < (SELECT MAX(SAL)
                                       FROM EMP
                                       WHERE SAL < (SELECT MAX(SAL)
                                                    FROM EMP))));

-- WAQTD NAME OF THE EMPLOYEE EARNING 3RD MAXIMUM SALARY
SELECT ENAME
FROM EMP
WHERE SAL = (SELECT MAX(SAL)
             FROM EMP
             WHERE SAL < (SELECT MAX(SAL)
                          FROM EMP
                          WHERE SAL < (SELECT MAX(SAL)
                                       FROM EMP)));

-- WAQTD EMPNO OF THE EMPLOYEE EARNING 2D MAXIMUM SALARY
SELECT EMPNO
FROM EMP
WHERE SAL = (SELECT MAX(SAL)
             FROM EMP
             WHERE SAL < (SELECT MAX(SAL)
                          FROM EMP));

-- WAQTD DEPARTMENT NAME OF AN EMPLOYEE GETTING 4TH MAX SAL
SELECT DNAME
FROM DEPT
WHERE DEPTNO IN (SELECT DEPTNO
                FROM EMP
                WHERE SAL = (SELECT MAX(SAL)
                             FROM EMP
                             WHERE SAL < (SELECT MAX(SAL)
                                          FROM EMP
                                          WHERE SAL < (SELECT MAX(SAL)
                                                       FROM EMP
                                                       WHERE SAL < (SELECT MAX(SAL)
                                                                    FROM EMP)))));

-- WAQTD DETAILS OF THE EMPLOYEE WHO WAS HIRED 2nd
SELECT *
FROM EMP
WHERE HIREDATE = (SELECT MIN(HIREDATE)
                  FROM EMP
                  WHERE HIREDATE > (SELECT MIN(HIREDATE)
                                    FROM EMP));

-- WAQTD NAME OF THE EMPLOYEE HIRED BEFORE THE LAST EMPLOYEE
SELECT ENAME
FROM EMP
WHERE HIREDATE = (SELECT MAX(HIREDATE)
                  FROM EMP
                  WHERE HIREDATE < (SELECT MAX(HIREDATE)
                                    FROM EMP));

-- WAQTD LOC OF THE EMPLOYEE WHO WAS HIRED FIRST 
SELECT LOC
FROM DEPT
WHERE DEPTNO IN (SELECT DEPTNO
                FROM EMP
                WHERE HIREDATE = (SELECT MIN(HIREDATE)
                                  FROM EMP));

-- WAQTD DETAILS OF THE EMPLOYEE EARNING 7TH MINIMUM SALARY 
SELECT *
FROM EMP
WHERE SAL = (SELECT MIN(SAL)
             FROM EMP
             WHERE SAL > (SELECT MIN(SAL)
                          FROM EMP
                          WHERE SAL > (SELECT MIN(SAL)
                                       FROM EMP
                                       WHERE SAL > (SELECT MIN(SAL)
                                                    FROM EMP
                                                    WHERE SAL > (SELECT MIN(SAL)
                                                                 FROM EMP
                                                                 WHERE SAL > (SELECT MIN(SAL)
                                                                              FROM EMP
                                                                              WHERE SAL > (SELECT MIN(SAL)
                                                                                           FROM EMP)))))));

-- WAQTD DNAME OF EMPLOYEE GETTING 2ND MAXIMUM SALARY
SELECT DNAME
FROM DEPT
WHERE DEPTNO IN (SELECT DEPTNO
                 FROM EMP
                 WHERE SAL = (SELECT MAX(SAL)
                              FROM EMP
                              WHERE SAL < (SELECT MAX(SAL)
                                           FROM EMP)));

-- WAQTD NAME OF THE EMPLOYEES EARNING SALARY MORE THAN THE SALESMAN
SELECT ENAME 
FROM EMP  
WHERE SAL > ANY(SELECT SAL 
                FROM EMP 
                WHERE JOB = 'SALESMAN');

-- WAQTD DETAILS OF THE EMPLOYEES HIRED AFTER ALL THE CLERKS
SELECT * 
FROM EMP 
WHERE HIREDATE > ALL(SELECT HIREDATE 
                     FROM EMP 
                     WHERE JOB = 'CLERK');

-- WAQTD NAME AND SALARY FOR ALL THE EMPLOYEES IF THEY ARE EARNING LESS THAN ATLEST A MANAGER
SELECT ENAME, SAL
FROM EMP
WHERE SAL < ANY(SELECT SAL 
                FROM EMP
                WHERE JOB = 'MANAGER');

-- WAQTD NAME AND HIREDATE OF EMPLOYEES HIRED BEFORE ALL THE MANAGERS
SELECT ENAME, HIREDATE
FROM EMP
WHERE HIREDATE < ALL(SELECT HIREDATE
                     FROM EMP
                     WHERE JOB = 'MANAGER');

-- WAQTD NAMES OF THE EMPLOYEES HIRED AFTER ALL THE MANAGERS AND EARNING SALARY MORE THAN ALL THE CLERKS
SELECT ENAME
FROM EMP
WHERE HIREDATE > ALL(SELECT HIREDATE
                     FROM EMP
                     WHERE JOB = 'MANAGER') AND SAL > ALL(SELECT SAL
                                                          FROM EMP
                                                          WHERE JOB = 'CLERK');

-- WAQTD DETAILS OF THE EMPLOYEES WORKING AS CLERK AND HIRED BEFORE ATLEST A SALESMAN
SELECT *
FROM EMP
WHERE JOB = 'CLERK' AND HIREDATE < ANY(SELECT HIREDATE
                                       FROM EMP
                                       WHERE JOB = 'SALESMAN');

-- WAQTD DETAILS OF EMPLOYEES WORKING IN ACCOUNTING OR SALES DEPT
SELECT * 
FROM EMP 
WHERE DEPTNO = ANY(SELECT DEPTNO 
                   FROM DEPT 
                   WHERE DNAME IN ('ACCOUNTING', 'SALES'));

-- WAQTD DEPARTMENT NAMES OF THE EMPOYEES WITH NAME SMITH , KING AND MILLER
SELECT DNAME 
FROM DEPT 
WHERE DEPTNO IN (SELECT DEPTNO 
                          FROM EMP 
                          WHERE ENAME IN ('SMITH', 'KING', 'MILLER'));

-- WAQTD DETAILS OF EMPLOYEES WORKING NEWYORK OR CHICAGO
SELECT * 
FROM EMP 
WHERE DEPTNO = ANY(SELECT DEPTNO 
                   FROM DEPT 
                   WHERE LOC IN ('NEW YORK', 'CHICAGO'));

-- WAQTD EMP NAMES IF EMPLOYEES ARE HIRED AFTER ALL THE EMPLOYEES OF DEPT 10 
SELECT ENAME
FROM EMP
WHERE HIREDATE > ALL(SELECT HIREDATE
                     FROM EMP
                     WHERE DEPTNO = 10);

-- EMP AND MANAGER RELATION.
-- WAQTD SMITHS REPORTING MANAGER'S NAME
SELECT ENAME
FROM EMP
WHERE EMPNO = (SELECT MGR
               FROM EMP
               WHERE ENAME = 'SMITH');

-- WAQTD ADAMS MANAGER'S MANAGER NAME
SELECT ENAME
FROM EMP
WHERE EMPNO = (SELECT MGR
               FROM EMP
               WHERE EMPNO = (SELECT MGR
                              FROM EMP
                              WHERE ENAME = 'ADAMS'));

-- WAQTD DNAME OF JONES MANAGER
SELECT DNAME
FROM DEPT
WHERE DEPTNO IN (SELECT DEPTNO
                 FROM EMP
                 WHERE EMPNO = (SELECT MGR
                                FROM EMP
                                WHERE ENAME = 'JONES'));

-- WAQTD MILLER'S MANAGER'S SALARY
SELECT SAL
FROM EMP
WHERE EMPNO = (SELECT MGR
               FROM EMP
               WHERE ENAME = 'MILLER');

-- WAQTD LOC OF SMITH'S MANAGER'S MANAGER.
SELECT LOC
FROM DEPT
WHERE DEPTNO = (SELECT DEPTNO
                FROM EMP
                WHERE EMPNO = (SELECT MGR
                               FROM EMP
                               WHERE EMPNO = (SELECT MGR
                                              FROM EMP
                                              WHERE ENAME = 'SMITH')));

-- WAQTD NAME OF THE EMPLOYEES REPORTING TO BLAKE
SELECT ENAME
FROM EMP
WHERE MGR = (SELECT EMPNO
             FROM EMP
             WHERE ENAME = 'BLAKE');

-- WAQTD NUMBER OF EMPLPOYEES REPORTING TO KING
SELECT COUNT(*)
FROM EMP
WHERE MGR = (SELECT EMPNO
             FROM EMP
             WHERE ENAME = 'KING');

-- WAQTD DETAILS OF THE EMPLOYEES REPORTING TO JONES
SELECT *
FROM EMP
WHERE MGR = (SELECT EMPNO
             FROM EMP
             WHERE ENAME = 'JONES');

-- WAQTD ENAMES OF THE EMPLOYEES REPORTING TO BLAKE'S MANAGER
SELECT ENAME 
FROM EMP 
WHERE MGR = (SELECT EMPNO 
             FROM EMP 
             WHERE EMPNO = (SELECT MGR 
                            FROM EMP 
                            WHERE ENAME = 'BLAKE'));

-- WAQTD NUMBER OF EMPLOYEES REPORTING TO FORD'S MANAGER 
SELECT COUNT(*)
FROM EMP 
WHERE MGR = (SELECT EMPNO 
             FROM EMP 
             WHERE EMPNO = (SELECT MGR 
                            FROM EMP 
                            WHERE ENAME = 'FORD'));

-- EXISTS & NOT EXISTS
-- Find departments where employees exist.
SELECT * 
FROM DEPT D 
WHERE EXISTS (SELECT 1 
              FROM EMP E 
              WHERE E.DEPTNO = D.DEPTNO);

-- Find departments where no employees exist.
SELECT * 
FROM DEPT D 
WHERE NOT EXISTS (SELECT 1 
                  FROM EMP E 
                  WHERE E.DEPTNO = D.DEPTNO);

-- Find employees who have a manager.
SELECT * 
FROM EMP E 
WHERE EXISTS (SELECT 1 
              FROM EMP M 
              WHERE M.EMPNO = E.MGR);

-- Find employees who do not report to anyone.
SELECT * 
FROM EMP E 
WHERE NOT EXISTS (SELECT 1 
                  FROM EMP M 
                  WHERE M.EMPNO = E.MGR);

-- Find departments having employees earning more than 3000.
SELECT * 
FROM DEPT D 
WHERE EXISTS (SELECT 1 
              FROM EMP E 
              WHERE E.DEPTNO = D.DEPTNO AND E.SAL > 3000);

-- Find departments where no employee earns more than 3000.
SELECT * 
FROM DEPT D 
WHERE NOT EXISTS (SELECT 1 
              FROM EMP E 
              WHERE E.DEPTNO = D.DEPTNO AND E.SAL > 3000);

-- Find employees who are managers of someone.
SELECT * 
FROM EMP E 
WHERE EXISTS (SELECT 1 
              FROM EMP M 
              WHERE M.MGR = E.EMPNO);

-- Find employees who are not managers of anyone.
SELECT * 
FROM EMP E 
WHERE NOT EXISTS (SELECT 1 
              FROM EMP M 
              WHERE M.MGR = E.EMPNO);


-- Find departments having at least one clerk.
SELECT * 
FROM DEPT D 
WHERE EXISTS (SELECT 1 
              FROM EMP E 
              WHERE E.DEPTNO = D.DEPTNO AND E.JOB = 'CLERK');

-- Find employees working in departments where at least one employee gets commission.
SELECT * 
FROM EMP E 
WHERE EXISTS (SELECT 1 
              FROM EMP M 
              WHERE M.DEPTNO = E.DEPTNO AND COMM IS NOT NULL AND  COMM > 0 );

-- CO-RELATED SUB QUERY
-- Find employees earning more than average salary of their department.
    SELECT * 
    FROM EMP E 
    WHERE E.SAL > (SELECT  AVG(M.SAL) 
                   FROM EMP M 
                   WHERE M.DEPTNO = E.DEPTNO);

-- Find employees earning maximum salary in their department.
    SELECT * 
    FROM EMP E  
    WHERE E.SAL = (SELECT MAX(SAL) 
                   FROM EMP M 
                   WHERE M.DEPTNO = E.DEPTNO);

--  Find employees hired after average hiredate of their department.
    SELECT * 
    FROM EMP E 
    WHERE E.HIREDATE > (SELECT AVG(HIREDATE) 
                        FROM EMP M 
                        WHERE M.DEPTNO = E.DEPTNO);

-- Find employees earning less than department average salary.
    SELECT * 
    FROM EMP E 
    WHERE SAL < (SELECT AVG(M.SAL) 
                 FROM EMP M 
                 WHERE M.DEPTNO = E.DEPTNO);

-- Find employees whose salary equals minimum salary of their department.
    SELECT * 
    FROM EMP E 
    WHERE E.SAL = (SELECT MIN(M.SAL) 
                   FROM EMP M 
                   WHERE M.DEPTNO = E.DEPTNO);

-- Find employees earning more than average salary of employees with same job.
    SELECT * 
    FROM EMP E  
    WHERE E.SAL > (SELECT AVG(SAL) 
                   FROM EMP M 
                   WHERE M.JOB = E.JOB);

-- Find employees hired earliest in each department.
    SELECT * 
    FROM EMP E 
    WHERE E.HIREDATE = (SELECT MIN(HIREDATE) 
                       FROM EMP M 
                       WHERE M.DEPTNO = E.DEPTNO);

-- Find employees earning highest salary in each job.
    SELECT * 
    FROM EMP E 
    WHERE E.SAL = (SELECT MAX(SAL) 
                    FROM EMP M 
                    WHERE M.JOB = E.JOB);

-- Find departments where at least one employee earns more than department average.
    SELECT DISTINCT E.DEPTNO 
    FROM EMP E 
    WHERE E.SAL > (SELECT AVG(SAL) 
                   FROM EMP M 
                   WHERE M.DEPTNO = E.DEPTNO) ;
    
-- Find employees earning more than manager salary.
     SELECT * 
     FROM EMP E 
     WHERE E.SAL > (SELECT SAL 
                    FROM EMP M 
                    WHERE M.EMPNO = E.MGR);
