--WAQTD THE ANNUAL SALARY OF THE EMPLOYEE WHOS NAME IS SMITH
SELECT ENAME, SAL*12 AS ANNUAL_SALARY FROM EMP WHERE ENAME = 'SMITH';

--WAQTD NAME OF THE EMPLOYEES WORKING AS CLERK
SELECT ENAME FROM EMP WHERE JOB = 'CLERK';

--WAQTD SALARY OF THE EMPLOYEES WHO ARE WORKING AS SALESMAN
SELECT SAL FROM EMP WHERE JOB = 'SALESMAN';

--WAQTD DETAILS OF THE EMP WHO EARNS MORE THAN 2000.
SELECT * FROM EMP WHERE SAL > 2000;

--WAQTD DETAILS OF THE EMP WHOS NAME IS JONES
SELECT * FROM EMP WHERE ENAME = 'JONES';

--WAQTD DETAILS OF THE EMP WHO WAS HIRED AFTER 01-JAN-81
SELECT * FROM EMP WHERE HIREDATE > '1981-01-01';

--WAQTD NAME AND SAL ALONG WITH HIS ANNUAL SALARY IF THE ANNUAL SALARY IS MORE THAN 12000
SELECT ENAME, SAL, SAL*12 AS ANNUAL_SALARY FROM EMP WHERE SAL*12 > 12000;

--WAQTD EMPNO OF THE EMPLOYEES WHO ARE WORKING IN DEPT 30
SELECT EMPNO FROM EMP WHERE DEPTNO = 30;

--WAQTD ENAME AND HIREDATE IF THEY ARE HIRED BEFORE 1981
SELECT ENAME, HIREDATE FROM EMP WHERE HIREDATE < '1981-01-01';

--WAQTD DETAILS OF THE EMPLOYEES WORKING AS MANAGER
SELECT * FROM EMP WHERE JOB = 'MANAGER';

--WAQTD NAME AND SALARY GIVEN TO AN EMPLOYEE IF EMPLOYEE EARNS A COMMISSION OF RUPEES 1400
SELECT ENAME, SAL FROM EMP WHERE COMM = 1400;

--WAQTD DETAILS OF EMPLOYEES HAVING COMMISSION MORE THAN SALARY 
SELECT * FROM EMP WHERE COMM > SAL;

--WAQTD EMPNO OF EMPLOYEES HIRED BEFORE THE YEAR 87
SELECT EMPNO FROM EMP WHERE HIREDATE < '1987-01-01';

--WAQTD DETAILS OF EMPLOYEES WORKING AS AN ANALYST
SELECT * FROM EMP WHERE JOB = 'ANALYST';

--WAQTD DETAILS OF EMPS EARNING MORE THAN 2000 RUPEES PER MONTH 
SELECT * FROM EMP WHERE SAL > 2000;
