--WAQTD THE ANNUAL SALARY OF THE EMPLOYEE WHOS NAME IS SMITH
SELECT ENAME, SAL*12 AS ANNUAL_SALARY FROM EMP WHERE ENAME = 'SMITH';

--WAQTD NAME OF THE EMPLOYEES WORKING AS CLERK
SELECT ENAME FROM EMP WHERE JOB = 'CLERK';

--WAQTD SALARY OF THE EMPLOYEES WHO ARE WORKING AS SALESMAN
SELECT SAL FROM EMP WHERE JOB = 'SALESMAN';

--WAQTD DETAILS OF THE EMP WHO EARNS MORE THAN 2000.
SELECT * FROM EMP WHERE SAL > 2000;

--WAQTD DETAILS OF THE EMP WHOS NAME IS JONES
SELECT * FROM EMP WHERE ENAME = 'JONES';

--WAQTD DETAILS OF THE EMP WHO WAS HIRED AFTER 01-JAN-81
SELECT * FROM EMP WHERE HIREDATE > '1981-01-01';

--WAQTD NAME AND SAL ALONG WITH HIS ANNUAL SALARY IF THE ANNUAL SALARY IS MORE THAN 12000
SELECT ENAME, SAL, SAL*12 AS ANNUAL_SALARY FROM EMP WHERE SAL*12 > 12000;

--WAQTD EMPNO OF THE EMPLOYEES WHO ARE WORKING IN DEPT 30
SELECT EMPNO FROM EMP WHERE DEPTNO = 30;

--WAQTD ENAME AND HIREDATE IF THEY ARE HIRED BEFORE 1981
SELECT ENAME, HIREDATE FROM EMP WHERE HIREDATE < '1981-01-01';

--WAQTD DETAILS OF THE EMPLOYEES WORKING AS MANAGER
SELECT * FROM EMP WHERE JOB = 'MANAGER';

--WAQTD NAME AND SALARY GIVEN TO AN EMPLOYEE IF EMPLOYEE EARNS A COMMISSION OF RUPEES 1400
SELECT ENAME, SAL FROM EMP WHERE COMM = 1400;

--WAQTD DETAILS OF EMPLOYEES HAVING COMMISSION MORE THAN SALARY 
SELECT * FROM EMP WHERE COMM > SAL;

--WAQTD EMPNO OF EMPLOYEES HIRED BEFORE THE YEAR 87
SELECT EMPNO FROM EMP WHERE HIREDATE < '1987-01-01';

--WAQTD DETAILS OF EMPLOYEES WORKING AS AN ANALYST
SELECT * FROM EMP WHERE JOB = 'ANALYST';

--WAQTD DETAILS OF EMPS EARNING MORE THAN 2000 RUPEES PER MONTH 
SELECT * FROM EMP WHERE SAL > 2000;

--WAQTD DETAILS OF THE EMPLOYEES WORKING AS CLERK AND EARNING LESS THAN 1500
SELECT * FROM EMP WHERE JOB = 'CLERK' AND SAL < 1500;

--WAQTD NAME AND HIREDATE OF THE EMPLOYEES WORKING AS MANAGER IN DEPT 30
SELECT ENAME, HIREDATE FROM EMP WHERE JOB = 'MANAGER' AND DEPTNO = 30;

--WAQTD DETAILS OF THE EMP ALONG WITH ANNUAL SALARY IF THEY ARE WORKING IN DEPT AS SALESMAN AND THEIR ANNUAL SALARY HAS TO BE GREATER THAN 14000.
SELECT *, SAL*12 AS ANNUAL_SAL FROM EMP WHERE DEPTNO = 30 AND JOB = 'SALESMAN' AND SAL*12 > 14000;

--WAQTD ALL THE DETAILS OF THE EMP WORKING IN DEPT 30 OR AS ANALYST
SELECT * FROM EMP WHERE DEPTNO = 30 OR JOB = 'ANALYST';

--WAQTD NAMES OF THE EMPMLOYEES WHOS SALARY IS LESS THAN 1100 AND THEIR DESIGNATION IS CLERK
SELECT ENAME FROM EMP WHERE SAL < 1100 AND JOB = 'CLERK';

--WAQTD NAME AND SAL , ANNUAL SAL AND DEPTNO IF DEPTNO IS 20 EARNING MORE THAN 1100 AND ANNUAL SALARY EXCEEDS 12000
SELECT ENAME, SAL, SAL*12 AS ANNUAL_SAL FROM EMP WHERE DEPTNO = 20 AND SAL > 1100 AND SAL*12 > 12000;

--WAQTD EMPNO AND NAMES OF THE EMPLOYEES WORKING AS MANAGER IN DEPT 20
 SELECT EMPNO, ENAME FROM EMP WHERE JOB = 'MANAGER' AND DEPTNO = 20;

--WAQTD DETAILS OF EMPLOYEES WORKING IN DEPT 20 OR 30 
SELECT * FROM EMP WHERE DEPTNO IN (20, 30);

--WAQTD DETAILS OF EMPLOYEES WORKING AS ANALYST IN DEPT 10 .
SELECT * FROM EMP WHERE JOB = 'ANALYST' AND DEPTNO = 10;

--WAQTD DETAILS OF EMPLOYEE WORKING AS PRESIDENT WITH SALARY OF RUPEES 5000
SELECT * FROM EMP WHERE JOB = 'PRESIDENT' AND SAL = 5000;

--WAQTD NAMES AND DEPTNO , JOB OF EMPS WORKING AS CLERK IN DEPT 10 OR 20 
SELECT ENAME, DEPTNO, JOB FROM EMP WHERE JOB = 'CLERK' AND DEPTNO IN (10, 20);

--WAQTD DETAILS OF EMPLOYEES WORKING AS CLERK OR MANAGER IN DEPT 10 .
SELECT * FROM EMP WHERE JOB IN ('CLERK', 'MANAGER') AND DEPTNO = 10;

--WAQTD NAMES OF EMPLOYEES WORKING IN DEPT 10 , 20 , 30 , 40 .
SELECT ENAME FROM EMP WHERE DEPTNO IN (10, 20, 30, 40);

--WAQTD DETAILS OF EMPLOYEES WITH EMPNO 7902,7839.
SELECT * FROM EMP WHERE EMPNO IN (7902, 7839);

--.WAQTD DETAILS OF EMPLOYEES WORKING AS MANAGER OR SALESMAN OR CLERK
SELECT * FROM EMP WHERE JOB IN ('MANAGER', 'SALESMAN', 'CLERK');

--WAQTD NAMES OF EMPLOYEES HIRED AFTER 81 AND BEFORE 87
SELECT ENAME FROM EMP WHERE HIREDATE > '1981-01-01' AND HIREDATE <'1987-01-01';

--WAQTD DETAILS OF EMPLOYEES EARNING MORE THAN 1250 BUT LESS THAN 3000 
SELECT * FROM EMP WHERE SAL > 1250 AND SAL < 3000;

--WAQTD NAMES OF EMPLOYEES HIRED AFTER 81 INTO DEPT 10 OR 30
SELECT ENAME FROM EMP WHERE HIREDATE > '1981-01-01' AND DEPTNO IN (10, 30);

--WAQTD NAMES OF EMPLOYEES ALONG WITH ANNUAL SALARY FOR THE EMPLOYEES WORKING AS MANAGER OR CLERK INTO DEPT 10 OR 30
SELECT ENAME, SAL*12 AS ANNUAL_SAL FROM EMP WHERE JOB IN ('MANAGER', 'CLERK') AND DEPTNO IN (10, 30);

--WAQTD ALL THE DETAILS ALONG WITH ANNUAL SALARY IF SAL IS BETWEEN 1000 AND 4000 ANNUAL SALARY MORE THAN 15000
SELECT *, SAL*12 AS ANNUAL_SAL FROM EMP WHERE SAL > 1000 AND SAL < 4000 AND SAL*12 > 15000;

--LIST ALL THE EMPLOYEES WHOSE COMMISSION IS NULL
SELECT * FROM EMP WHERE COMM IS NULL;

--LIST ALL THE EMPLOYEES WHO DON’T HAVE A REPORTING MANAGER
SELECT * FROM EMP WHERE MGR IS NULL;

-- LIST ALL THE SALESMEN IN DEPT 30
SELECT * FROM EMP WHERE JOB = 'SALESMAN' AND DEPTNO = 30;

--LIST ALL THE SALESMEN IN DEPT NUMBER 30 AND HAVING SALARY GREATER THAN 1500
SELECT * FROM EMP WHERE JOB = 'SALESMAN' AND DEPTNO = 30 AND SAL > 1500;

-- LIST ALL THE EMPLOYEES WHOSE NAME STARTS WITH ‘S’ OR ‘A’
SELECT * FROM EMP WHERE ENAME LIKE 'S%' OR ENAME LIKE 'A%';

-- LIST ALL THE EMPLOYEES EXCEPT THOSE WHO ARE WORKING IN DEPT 10 & 20.
SELECT * FROM EMP WHERE DEPTNO NOT IN (10, 20);

--LIST THE EMPLOYEES WHOSE NAME DOES NOT START WITH ‘S’
SELECT * FROM EMP WHERE ENAME NOT LIKE 'S%';

--LIST ALL THE EMPLOYEES WHO ARE HAVING REPORTING MANAGERS IN DEPT 10
SELECT * FROM EMP WHERE MGR IS NOT NULL AND DEPTNO = 10;

-- LIST ALL THE EMPLOYEES WHOSE COMMISSION IS NULL AND WORKING AS CLERK
SELECT * FROM EMP WHERE COMM IS NULL AND JOB = 'CLERK';

-- LIST ALL THE EMPLOYEES WHO DON’T HAVE A REPORTING MANAGER IN DEPTNO 10 OR 30
SELECT * FROM EMP WHERE MGR IS NULL AND DEPTNO IN (10, 30);

-- LIST ALL THE SALESMEN IN DEPT 30 WITH SAL MORE THAN 2450
SELECT * FROM EMP WHERE JOB = 'SALESMAN' AND DEPTNO = 30 AND SAL > 2450;

-- LIST ALL THE ANALYST IN DEPT NUMBER 20 AND HAVING SALARY GREATER THAN 2500
SELECT * FROM EMP WHERE JOB = 'ANALYST' AND DEPTNO = 20 AND SAL > 2500;

--LIST ALL THE EMPLOYEES WHOSE NAME STARTS WITH ‘M’ OR ‘J’
SELECT * FROM EMP WHERE ENAME LIKE 'M%' OR ENAME LIKE 'J%';

--LIST ALL THE EMPLOYEES WITH ANNUAL SALARY EXCEPT THOSE WHO ARE WORKING IN DEPT 30
SELECT *, SAL*12 ANNUAL_SAL FROM EMP WHERE DEPTNO NOT IN (30);

-- LIST THE EMPLOYEES WHOSE NAME DOES NOT END WITH ‘ES’ OR ‘R’
SELECT * FROM EMP WHERE ENAEM NOT LIKE '%ES' AND ENAME NOT LIKE '%R';

-- LIST ALL THE EMPLOYEES WHO ARE HAVING REPORTING MANAGERS IN DEPT 10 ALONG WITH 10% HIKE IN SALARY
SELECT *, SAL+(SAL*10/100) AS SALARY_HIKE FROM EMP WHERE MGR IS NOT NULL AND DEPTNO = 10;

-- DISPLAY ALL THE EMPLOYEE WHO ARE ‘SALESMAN’S HAVING ‘E’ AS THE LAST BUT ONE CHARACTER IN ENAME BUT SALARY HAVING EXACTLY 4 CHARACTER
SELECT * FROM EMP WHERE JOB = 'SALESMAN' AND ENAME LIKE '%E_' AND SAL LIKE ____;

-- DISPLAY ALL THE EMPLOYEE WHO ARE JOINED AFTER YEAR 81
SELECT * FROM EMP WHERE HIREDATE > '1981-01-01';

--DISPLAY ALL THE EMPLOYEE WHO ARE JOINED IN FEB
SELECT * FROM EMP WHERE HIREDATE LIKE '%02%';

-- LIST THE EMPLOYEES WHO ARE NOT WORKING AS MANAGERS AND CLERKS IN DEPT 10 AND 20 WITH A SALARY IN THE RANGE OF 1000 TO 3000.
SELECT * FROM EMP WHERE JOB NOT IN ('MANAGER', 'CLERK') AND DEPTNO IN (10, 20) AND SAL BETWEEN 1000 AND 3000;
