-- Create Customers table
CREATE TABLE CUSTOMERS( 
  CUSTOMER_ID INT PRIMARY KEY, 
  NAME VARCHAR(10) NOT NULL, 
  CITY VARCHAR(20) NOT NULL, 
  EMAIL VARCHAR(20) NOT NULL
);

-- Create Orders table
CREATE TABLE ORDERS( 
  ORDER_ID INT PRIMARY KEY, 
  CUSTOMER_ID INT, 
  FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID), 
  ORDER_DATE DATE NOT NULL
);

-- Create Product table
 CREATE TABLE PRODUCT(
   PRODUCT_ID INT PRIMARY KEY, 
   PRODUCT_NAME VARCHAR(20) NOT NULL, 
   PRICE INT NOT NULL
  );

-- Create Order_items table
CREATE TABLE ORDERS_ITEMS(
  ORDER_ITEM_ID INT PRIMARY KEY, 
  ORDER_ID INT, 
  FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID), 
  PRODUCT_ID INT, 
  FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID), 
  QUANTITY INT NOT NULL
);

