-- Show all customers.
SELECT *
FROM CUSTOMERS;

-- Show only customer names and cities.
SELECT NAME, CITY
FROM CUSTOMERS;

-- Display all products with their prices.
SELECT PRODUCT_NAME, PRICE
FROM PRODUCT;

-- Show all orders.
SELECT *
FROM ORDERS;

-- Display product names only.
SELECT PRODUCT_NAME
FROM PRODUCT;

-- Show customers who live in Pune.
SELECT *
FROM CUSTOMERS
WHERE CITY = 'PUNE';

-- Show products with price greater than 10,000.
SELECT PRODUCT_NAME, PRICE
FROM PRODUCT
WHERE PRICE > 10000;

-- Show orders placed after 2024-01-12.
SELECT *
FROM ORDERS
WHERE ORDER_DATE > '2024-01-12';

-- Show customers whose name starts with 'S'.
SELECT *
FROM CUSTOMERS
WHERE NAME LIKE 'S%';

-- Show products with price between 1000 and 5000.
SELECT PRODUCT_NAME, PRICE
FROM PRODUCT
WHERE PRICE BETWEEN 1000 AND 5000;

-- Show product name and price + 500 as increased_price.
SELECT PRODUCT_NAME, PRICE, PRICE+500 AS INCREASED_PRICE 
FROM PRODUCT;

-- Show product name and price with 10% discount.
SELECT PRODUCT_NAME, PRICE, PRICE-(PRICE*10/100) AS DISCOUNT 
FROM PRODUCT;

-- Show order_id and quantity * 2 as double_quantity.
SELECT ORDER_ID, QUANTITY, QUANTITY*2 AS DOUBLE_QUANTITY 
FROM ORDERS_ITEMS;

-- Show product price in thousands (price / 1000).
SELECT PRICE, PRICE/1000
FROM PRODUCT;

-- Show customer name in uppercase.
SELECT UPPER(NAME)
FROM CUSTOMERS;

-- Show products with price after 10% discount where price > 5000.
SELECT PRODUCT_NAME, PRICE, PRICE-(PRICE*10/100) AS DISCOUNT 
FROM PRODUCT 
WHERE PRICE-(PRICE*10/100) > 5000;

-- Show customers from Pune in uppercase.
SELECT UPPER(NAME) 
FROM CUSTOMERS 
WHERE CITY = 'PUNE';

-- Show products where price + 1000 > 5000.
SELECT PRODUCT_NAME 
FROM PRODUCT 
WHERE PRICE+1000> 5000;

-- Show order_items where quantity * price (hint: join later if needed, try basic first).
SELECT O.ORDER_ITEM_ID, O.ORDER_ID, O.PRODUCT_ID, (O.QUANTITY*P.PRICE) AS TOTAL_PRICE 
FROM ORDERS_ITEMS O INNER JOIN PRODUCT P 
ON O.PRODUCT_ID = P.PRODUCT_ID;

-- Show products whose name contains 'o'.
SELECT PRODUCT_NAME 
FROM PRODUCT 
WHERE PRODUCT_NAME LIKE '%O%';

-- Show products where price is even.
SELECT * 
FROM PRODUCT 
WHERE MOD(PRICE, 2) = 0;

-- Show customers whose email contains gmail.
SELECT * 
FROM CUSTOMERS 
WHERE EMAIL LIKE '%GMAIL%';

-- Show orders placed in January month only.
SELECT * 
FROM ORDERS 
WHERE DATE_FORMAT(ORDER_DATE, '%M') = 'JANUARY';

-- Show products sorted by price (ascending).
SELECT * 
FROM PRODUCT 
ORDER BY PRICE ASC;

-- Show top 3 expensive products.
SELECT * 
FROM PRODUCT 
ORDER BY PRICE DESC 
LIMIT 3;

-- Show product name with label: - If price > 50000 → 'Expensive' - Else → 'Affordable'
SELECT PRODUCT_NAME, 
CASE
   WHEN PRICE > 50000 THEN 'EXPENSIVE'
   ELSE 'AFFORDABLE'
END AS LABEL
FROM PRODUCT;

-- Count total number of customers in each city.
SELECT CITY, COUNT(*) AS TOTAL_CUSTOMER
FROM CUSTOMERS 
GROUP BY CITY;

-- Find total number of orders placed by each customer.
SELECT C.NAME, COUNT(*) AS TOTAL_ORDER
FROM CUSTOMERS C INNER JOIN ORDERS O
ON  C.CUSTOMER_ID = O.CUSTOMER_ID
GROUP BY C.NAME;

-- Find total quantity of products sold for each product_id.
SELECT PRODUCT_ID, SUM(QUANTITY) AS TOTAL_QUANTITY
FROM ORDERS_ITEMS 
GROUP BY PRODUCT_ID;

-- Find maximum price of products.
SELECT PRODUCT_NAME, PRICE 
FROM PRODUCT 
WHERE PRICE = (SELECT MAX(PRICE) 
               FROM PRODUCT);

-- Find minimum price of products.
SELECT PRODUCT_NAME, PRICE 
FROM PRODUCT 
WHERE PRICE = (SELECT MAX(PRICE) 
               FROM PRODUCT);

-- Show customer name and total number of orders placed.
SELECT C.NAME, COUNT(*) AS TOTAL_ORDER 
FROM CUSTOMERS C INNER JOIN ORDERS O 
ON C.CUSTOMER_ID = O.CUSTOMER_ID 
GROUP BY C.CUSTOMRE_ID ,C.NAME;

-- Show product name and total quantity sold.
SELECT P.PRODUCT_NAME, SUM(O.QUANTITY) AS TOTAL_QUANTITY 
FROM PRODUCT P INNER JOIN ORDERS_ITEMS O 
ON P.PRODUCT_ID = O.PRODUCT_ID 
GROUP BY P.PRODUCT_ID, P.PRODUCT_NAME;

-- Show each order_id and total quantity of items in that order.
SELECT O.ORDER_ID, SUM(OI.QUANTITY) AS TOTAL_QUANTITY
FROM ORDERS O INNER JOIN ORDERS_ITEMS OI 
ON O.ORDER_ID = OI.ORDER_ID 
GROUP BY O.ORDER_ID;

-- Show customer name and total quantity of products they ordered.
SELECT C.NAME, SUM(OI.QUANTITY) AS TOTAL_QUANTITY
FROM CUSTOMERS C INNER JOIN ORDERS O 
ON C.CUSTOMER_ID = O.CUSTOMER_ID 
INNER JOIN ORDERS_ITEMS OI 
ON O.ORDER_ID = OI.ORDER_ID 
GROUP BY C.CUSTOMER_ID, C.NAME;

-- Show total revenue for each product.
SELECT P.PRODUCT_NAME, SUM(O.QUANTITY * P.PRICE) AS TOTAL_REVENUE 
FROM PRODUCT P INNER JOIN ORDERS_ITEMS O  
ON P.PRODUCT_ID = O.PRODUCT_ID 
GROUP BY P.PRODUCT_ID, P.PRODUCT_NAME;

--
-- Show customers who placed more than 1 order.
SELECT C.NAME, COUNT(*) AS TOTAL_ORDER
FROM CUSTOMERS C INNER JOIN ORDERS O 
ON C.CUSTOMER_ID = O.CUSTOMER_ID INNER JOIN ORDERS_ITEMS OI 
ON O.ORDER_ID = OI.ORDER_ID 
GROUP BY C.CUSTOMER_ID, C.NAME
HAVING COUNT(*) > 1;

-- Show products with total quantity sold greater than 2.
SELECT P.PRODUCT_NAME, SUM(O.QUANTITY) AS TOTAL_QUANTITY 
FROM PRODUCT P INNER JOIN ORDERS_ITEMS O 
ON P.PRODUCT_ID = O.PRODUCT_ID 
GROUP BY P.PRODUCT_ID, P.PRODUCT_NAME
HAVING SUM(O.QUANTITY) > 2;

-- Show cities having more than 1 customer.
SELECT CITY, COUNT(*)AS TOTAL_CUSTOMER
FROM CUSTOMERS 
GROUP BY CITY 
HAVING COUNT(*) > 1;

-- Show orders where total quantity > 2.
SELECT ORDER_ID, SUM(QUANTITY) AS TOTAL_QUANTITY
FROM ORDERS_ITEMS 
GROUP BY ORDER_ITEM_ID 
HAVING SUM(QUANTITY) > 2;

-- Show products whose price is greater than average price.
SELECT * 
FROM PRODUCT
WHERE PRICE > (SELECT AVG(PRICE) 
               FROM PRODUCT);

-- Show customer_id and total orders where total orders > 1.
SELECT C.CUSTOMER_ID, COUNT(*) AS TOTAL_ORDER
FROM CUSTOMERS C INNER JOIN ORDERS O 
ON C.CUSTOMER_ID = O.CUSTOMER_ID 
GROUP BY C.CUSTOMER_ID 
HAVING COUNT(*) > 1;

-- Show product_id and total quantity sold where quantity > 2.
SELECT P.PRODUCT_ID, SUM(O.QUANTITY) AS TOTAL_QUANTITY
FROM PRODUCT P INNER JOIN ORDERS_ITEMS O 
ON P.PRODUCT_ID = O.PRODUCT_ID 
GROUP BY P.PRODUCT_ID 
HAVING SUM(O.QUANTITY) > 2;

-- Show order_id where total items in order > 2.
SELECT ORDER_ID 
FROM ORDERS_ITEMS 
GROUP BY ORDER_ID 
HAVING SUM(QUANTITY)>2;

-- Show cities where number of customers > 1.
SELECT CITY 
FROM CUSTOMERS 
GROUP BY CITY 
HAVING COUNT(*) > 1;

-- Show products where total revenue > 50000.
SELECT P.PRODUCT_NAME 
FROM PRODUCT P INNER JOIN ORDERS_ITEMS O 
ON P.PRODUCT_ID = O.PRODUCT_ID 
GROUP BY P.PRODUCT_ID, P.PRODUCT_NAME 
HAVING SUM(O.QUANTITY*P.PRICE) > 50000;

--
-- Show customer who spent the most money.
SELECT C.NAME, SUM(OI.QUANTITY * P.PRICE) AS TOTAL_SPENT
FROM CUSTOMERS C INNER JOIN ORDERS O 
ON C.CUSTOMER_ID = O.CUSTOMER_ID
INNER JOIN ORDERS_ITEMS OI 
ON O.ORDER_ID = OI.ORDER_ID
INNER JOIN PRODUCT P 
ON OI.PRODUCT_ID = P.PRODUCT_ID
GROUP BY C.CUSTOMER_ID, C.NAME
ORDER BY TOTAL_SPENT DESC
LIMIT 1;

-- Show product which generated highest revenue.
SELECT P.PRODUCT_NAME, SUM(O.QUANTITY * P.PRICE) AS TOTAL_REVENUE
FROM PRODUCT P INNER JOIN ORDERS_ITEMS O 
ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY P.PRODUCT_ID, P.PRODUCT_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 1;

-- Show top 2 customers by total orders.
 SELECT C.NAME, COUNT(O.ORDER_ID) AS TOTAL_ORDER 
 FROM CUSTOMERS C INNER JOIN ORDERS O 
 ON C.CUSTOMER_ID = O.CUSTOMER_ID 
 GROUP BY C.CUSTOMER_ID, C.NAME 
 ORDER BY TOTAL_ORDER DESC 
 LIMIT 2;

-- Show average order value per customer.
SELECT C.NAME, AVG(OI.QUANTITY * P.PRICE) AS AVG_ORDER_VALUE
FROM CUSTOMERS C INNER JOIN ORDERS O 
ON C.CUSTOMER_ID = O.CUSTOMER_ID
INNER JOIN ORDERS_ITEMS OI 
ON O.ORDER_ID = OI.ORDER_ID
INNER JOIN PRODUCT P
ON OI.PRODUCT_ID = P.PRODUCT_ID
GROUP BY C.CUSTOMER_ID, C.NAME;

-- Show customers who never placed any order.
SELECT C.*
FROM CUSTOMERS C
LEFT JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
WHERE O.ORDER_ID IS NULL;

-- Show customer name and label: - If total spending > 50000 → 'VIP' - Else → 'NORMAL
SELECT C.NAME, 
CASE 
  WHEN SUM(OI.QUANTITY * P.PRICE) > 50000 THEN 'VIP' 
  ELSE 'NORMAL' 
END AS LABEL
FROM CUSTOMERS C
LEFT JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
LEFT JOIN ORDERS_ITEMS OI ON O.ORDER_ID = OI.ORDER_ID
LEFT JOIN PRODUCT P ON OI.PRODUCT_ID = P.PRODUCT_ID
GROUP BY C.CUSTOMER_ID, C.NAME;
